### ISSUE TITLE
Error during "mvn clean install" app-3

### ISSUE THREAD

**Issue by DwarfNumber2** [payneteasy/reader-example#1]
[ERROR] Failed to execute goal on project client: Could not resolve dependencies for project com.payneteasy.reader-example.app-3-webstart:client:jar:1.0-1-SNAPSHOT: The following artifacts could not be resolved: gnu.io.rxtx:rxtx-api:jar:2.2-stabilize-SNAPSHOT, gnu.io.rxtx:rxtxSerial:jar:2.2-stabilize-SNAPSHOT: Could not find artifact gnu.io.rxtx:rxtx-api:jar:2.2-stabilize-SNAPSHOT in reader-repo (http://paynet-qa.clubber.me/reader/maven)

**Comment by evsinev** [comment]
Before building reader example you need to build the rxtx project - https://github.com/rxtx/rxtx

**Comment by DwarfNumber2** [comment]
Another, but very similar error after rxtx building

[ERROR] Failed to execute goal on project client: Could not resolve dependencies for project com.payneteasy.reader-example.app-3-webstart:client:jar:1.0-1-SNAPSHOT: The following artifacts could not be resolved: gnu.io.rxtx:rxtx-api:jar:2.2-stabilize-SNAPSHOT, gnu.io.rxtx:rxtxSerial:jar:2.2-stabilize-SNAPSHOT: Failure to find gnu.io.rxtx:rxtx-api:jar:2.2-stabilize-SNAPSHOT in http://paynet-qa.clubber.me/reader/maven was cached in the local repository, resolution will not be reattempted until the update interval of reader-repo has elapsed or updates are forced -> [Help 1]

**Comment by evsinev** [comment]
Have you got an gnu.io.rxtx:rxtx-api:jar:2.2-stabilize-SNAPSHOT artefact directory in you local maven repository?

For example:
```
ls -l ~/.m2/repository/gnu/io/rxtx/rxtx-api/2.2-stabilize-SNAPSHOT
total 80
-rw-r--r--  1 esinev  staff    202 Sep 16 21:30 _maven.repositories
-rw-r--r--  1 esinev  staff    729 Sep 16 21:30 maven-metadata-local.xml
-rw-r--r--  1 esinev  staff    221 Sep 16 19:35 resolver-status.properties
-rw-r--r--  1 esinev  staff  22936 Sep 16 21:30 rxtx-api-2.2-stabilize-SNAPSHOT.jar
-rw-r--r--  1 esinev  staff   1651 Oct 13  2014 rxtx-api-2.2-stabilize-SNAPSHOT.pom
```

**Comment by DwarfNumber2** [comment]
Smth strange there...

sudo ls -l ~/.m2/repository/gnu/io/rxtx/rxtx-api/2.2-stabilize-SNAPSHOT
итого 12
-rw-rw-r-- 1 dwarf_2 dwarf_2 221 сент. 22 23:03 resolver-status.properties
-rw-rw-r-- 1 dwarf_2 dwarf_2 245 сент. 22 23:03 rxtx-api-2.2-stabilize-SNAPSHOT.jar.lastUpdated
-rw-rw-r-- 1 dwarf_2 dwarf_2 245 сент. 22 23:03 rxtx-api-2.2-stabilize-SNAPSHOT.pom.lastUpdated

**Comment by evsinev** [comment]
Maven has cached a response from the http://paynet-qa.clubber.me/reader/maven repository and shows this wrong error.
I suggest you to delete the ~/.m2/repository/gnu/io/rxtx directory and rerun the rxtx build again.

**Comment by DwarfNumber2** [comment]
Still the same error. 

I have removed  cache folder, ran(configure+make+make install on rxtx)+ mvn clean install on test example.

**Comment by evsinev** [comment]
Could you please attach the rxtx project build log.

**Comment by DwarfNumber2** [comment]
dwarf_2@dwarf-2:~/libs/rxtx-2.1-7r2$ make install
make  all-am
make[1]: Вход в каталог `/home/dwarf_2/libs/rxtx-2.1-7r2'
make[1]: Выход из каталога `/home/dwarf_2/libs/rxtx-2.1-7r2'
/usr/bin/install -c x86_64-unknown-linux-gnu/.libs/librxtxSerial-2.1-7.so /usr/lib/jvm/java-8-oracle/jre/lib/amd64/librxtxSerial-2.1-7.so
(cd /usr/lib/jvm/java-8-oracle/jre/lib/amd64 && rm -f librxtxSerial.so && ln -s librxtxSerial-2.1-7.so librxtxSerial.so)
/usr/bin/install -c x86_64-unknown-linux-gnu/.libs/librxtxSerial.lai /usr/lib/jvm/java-8-oracle/jre/lib/amd64/librxtxSerial.la
/usr/bin/install -c x86_64-unknown-linux-gnu/.libs/librxtxParallel-2.1-7.so /usr/lib/jvm/java-8-oracle/jre/lib/amd64/librxtxParallel-2.1-7.so
(cd /usr/lib/jvm/java-8-oracle/jre/lib/amd64 && rm -f librxtxParallel.so && ln -s librxtxParallel-2.1-7.so librxtxParallel.so)
/usr/bin/install -c x86_64-unknown-linux-gnu/.libs/librxtxParallel.lai /usr/lib/jvm/java-8-oracle/jre/lib/amd64/librxtxParallel.la
/usr/bin/install -c x86_64-unknown-linux-gnu/.libs/librxtxI2C-2.1-7.so /usr/lib/jvm/java-8-oracle/jre/lib/amd64/librxtxI2C-2.1-7.so
(cd /usr/lib/jvm/java-8-oracle/jre/lib/amd64 && rm -f librxtxI2C.so && ln -s librxtxI2C-2.1-7.so librxtxI2C.so)
/usr/bin/install -c x86_64-unknown-linux-gnu/.libs/librxtxI2C.lai /usr/lib/jvm/java-8-oracle/jre/lib/amd64/librxtxI2C.la
/usr/bin/install -c x86_64-unknown-linux-gnu/.libs/librxtxRaw-2.1-7.so /usr/lib/jvm/java-8-oracle/jre/lib/amd64/librxtxRaw-2.1-7.so
(cd /usr/lib/jvm/java-8-oracle/jre/lib/amd64 && rm -f librxtxRaw.so && ln -s librxtxRaw-2.1-7.so librxtxRaw.so)
/usr/bin/install -c x86_64-unknown-linux-gnu/.libs/librxtxRaw.lai /usr/lib/jvm/java-8-oracle/jre/lib/amd64/librxtxRaw.la
/usr/bin/install -c x86_64-unknown-linux-gnu/.libs/librxtxRS485-2.1-7.so /usr/lib/jvm/java-8-oracle/jre/lib/amd64/librxtxRS485-2.1-7.so
(cd /usr/lib/jvm/java-8-oracle/jre/lib/amd64 && rm -f librxtxRS485.so && ln -s librxtxRS485-2.1-7.so librxtxRS485.so)
/usr/bin/install -c x86_64-unknown-linux-gnu/.libs/librxtxRS485.lai /usr/lib/jvm/java-8-oracle/jre/lib/amd64/librxtxRS485.la
PATH="$PATH:/sbin" ldconfig -n /usr/lib/jvm/java-8-oracle/jre/lib/amd64
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/lib/jvm/java-8-oracle/jre/lib/amd64

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
/usr/bin/install -c RXTXcomm.jar /usr/lib/jvm/java-8-oracle/jre/lib/ext/

**Comment by evsinev** [comment]
There are a few problems in your rxtx build:
1. rxtx-2.1-7r2 is not from the master branch
2. you use make command to build the project instead of maven

I suggest you to checkout master branch from git repository and build using maven
```
git clone https://github.com/rxtx/rxtx.git
mvn clean install
```
The final output of the building process must be similar like this:
```
[INFO] Installing /Users/esinev/Downloads/src/rxtx/rxtxSerial-test/pom.xml to /Users/esinev/.m2/repository/gnu/io/rxtx/rxtxSerial-test/2.2-stabilize-SNAPSHOT/rxtxSerial-test-2.2-stabilize-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] RXTX parent POM ................................... SUCCESS [0.132s]
[INFO] Cross toolchain wrapper ........................... SUCCESS [0.510s]
[INFO] RXTX API .......................................... SUCCESS [1.550s]
[INFO] rxtxSerial java ................................... SUCCESS [0.505s]
[INFO] rxtxSerial native ................................. SUCCESS [0.029s]
[INFO] [osx/x86_64] rxtxSerial ........................... SUCCESS [2.179s]
[INFO] rxtxSerial binaries ............................... SUCCESS [0.029s]
[INFO] RXTX default serial driver ........................ SUCCESS [0.025s]
[INFO] rxtxSerial integration tests ...................... SUCCESS [0.020s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by DwarfNumber2** [comment]
Your way of installing produce error, during rxtx build:
[INFO] Reactor Summary:
[INFO] 
[INFO] RXTX parent POM ................................... SUCCESS [0.387s]
[INFO] Cross toolchain wrapper ........................... SUCCESS [1.161s]
[INFO] RXTX API .......................................... SUCCESS [4.084s]
[INFO] rxtxSerial java ................................... FAILURE [1.414s]
[INFO] rxtxSerial native ................................. SKIPPED
[INFO] [linux/x86_64] rxtxSerial ......................... SKIPPED
[INFO] rxtxSerial binaries ............................... SKIPPED
[INFO] RXTX default serial driver ........................ SKIPPED
[INFO] rxtxSerial integration tests ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.063s
[INFO] Finished at: Wed Sep 23 10:46:30 MSK 2015
[INFO] Final Memory: 26M/109M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project rxtxSerial-java: Compilation failure
[ERROR] /home/dwarf_2/libs/rxtx/rxtxSerial-java/src/main/java/gnu/io/impl/serial/RXTXPort.java:[181,8] error: constructor SerialPort in class SerialPort cannot be applied to given types;




I was trying to download zip sources from master branch and build was succes, but rxtx serial was not included in this build

k/2.2-stabilize-SNAPSHOT/rxtx-pack-2.2-stabilize-SNAPSHOT-dist.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] RXTX parent POM ................................... SUCCESS [0.363s]
[INFO] Cross toolchain wrapper ........................... SUCCESS [1.091s]
[INFO] RXTX java wrapper ................................. SUCCESS [4.185s]
[INFO] RXTX native source ................................ SUCCESS [0.177s]
[INFO] [linux/x86_64] RXTX native lib .................... SUCCESS [4.222s]
[INFO] RXTX packaging .................................... SUCCESS [0.187s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ----------------------

**Comment by evsinev** [comment]
I've just test the rxtx build on a new machine with Centos 5.10.
(assumes gcc, git are installed and java is in the /opt/jdk1.8.0_51
```
cd /tmp
wget http://apache-mirror.rbc.ru/pub/apache/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
tar xf apache-maven-3.3.3-bin.tar.gz
export JAVA_HOME=/opt/jdk1.8.0_51
export PATH=$PATH:$JAVA_HOME/bin
git clone https://github.com/rxtx/rxtx.git
cd rxtx
../apache-maven-3.3.3/bin/mvn clean install
```

**Comment by evsinev** [comment]
I've just upload ~/.m2/repository/gnu/io/rxtx to http://paynet-qa.clubber.me/reader/rxtx-maven-dir.tgz

```
cd ~/.m2/repository/gnu/io
wget http://paynet-qa.clubber.me/reader/rxtx-maven-dir.tgz
tar xf rxtx-maven-dir.tgz
```

**Comment by DwarfNumber2** [comment]
Thank you for sources. Have the same contents of artefact directory in local maven repository.
But still have an error...
[ERROR] Failed to execute goal on project client: Could not resolve dependencies for project com.payneteasy.reader-example.app-3-webstart:client:jar:1.0-1-SNAPSHOT: Failure to find gnu.io.rxtx:rxtxSerial:jar:2.2-stabilize-SNAPSHOT in http://paynet-qa.clubber.me/reader/maven was cached in the local repository, resolution will not be reattempted until the update interval of reader-repo has elapsed or updates are forced -> [Help 1]

dwarf_2@dwarf-2:~$ ls -l ~/.m2/repository/gnu/io/rxtx/rxtx-api/2.2-stabilize-SNAPSHOT
итого 52
-rw-rw-r-- 1 dwarf_2 dwarf_2   729 сент. 23 12:17 maven-metadata-local.xml
-rw-rw-r-- 1 dwarf_2 dwarf_2   202 сент. 23 12:17 _maven.repositories
-rw-rw-r-- 1 dwarf_2 dwarf_2   209 сент. 23 10:13 _remote.repositories
-rw-rw-r-- 1 dwarf_2 dwarf_2   221 сент. 23 00:34 resolver-status.properties
-rw-rw-r-- 1 dwarf_2 dwarf_2 22867 сент. 23 12:17 rxtx-api-2.2-stabilize-SNAPSHOT.jar
-rw-rw-r-- 1 dwarf_2 dwarf_2   245 сент. 23 00:34 rxtx-api-2.2-stabilize-SNAPSHOT.jar.lastUpdated
-rw-rw-r-- 1 dwarf_2 dwarf_2  1651 сент. 23 09:35 rxtx-api-2.2-stabilize-SNAPSHOT.pom
-rw-rw-r-- 1 dwarf_2 dwarf_2   245 сент. 23 00:34 rxtx-api-2.2-stabilize-SNAPSHOT.pom.lastUpdated

**Comment by evsinev** [comment]
Is your maven version 3.3.3 ?

Do you have ~/.m2/repository/gnu/io/rxtx/rxtxSerial/2.2-stabilize-SNAPSHOT directory ?
```
ls -l ~/.m2/repository/gnu/io/rxtx/rxtxSerial/2.2-stabilize-SNAPSHOT
total 60
-rw-rw-r-- 1 paynet paynet   731 Sep 23 10:13 maven-metadata-local.xml
-rw-rw-r-- 1 paynet paynet   213 Sep 23 10:13 _remote.repositories
-rw-rw-r-- 1 paynet paynet 47249 Sep 23 10:13 rxtxSerial-2.2-stabilize-SNAPSHOT.jar
-rw-rw-r-- 1 paynet paynet  2028 Sep 23 10:13 rxtxSerial-2.2-stabilize-SNAPSHOT.pom
```

**Comment by DwarfNumber2** [comment]
No, I attached log a few messages later about errors, during building sources of rxtx.

Can you upload rxtxSerial to  http://paynet-qa.clubber.me/reader/ too? 

Was trying to do smth with mvn install - nothing helps.

**Comment by evsinev** [comment]
The http://paynet-qa.clubber.me/reader/rxtx-maven-dir.tgz contains all directories for rxtx maven subtree.
When you extract rxtx-maven-dir.tgz in the ~/.m2/repository/gnu/io  maven will find it.

**Comment by evsinev** [comment]
Also you could tell maven do not fetch artefacts from remote repositories with the --offline option:
```
cd reader-example/app-3-webstart
mvn --offline clean install
```

**Comment by DwarfNumber2** [comment]
Ok, that helps me finally, thank you!

Now there are several problems with app3. 

1) server folder does not have file assemble.sh
2) after running create-storage.sh assemble.sh in client folder 
+ cp target/client-1.0-1-SNAPSHOT-jar-with-dependencies.jar ../server/src/main/resources/web/mpos.jar
+ jarsigner -keystore store.ks -storepass password -keypass password ../server/src/main/resources/web/mpos.jar alias-name
jar signed.

and mvn assembly:single in server folder, I have working example of page. But after running jnlp I get an exception:
com.sun.deploy.net.JARSigningException: Found unsigned entry in resource: http://localhost:8080/mpos.jar
	at com.sun.javaws.security.SigningInfo.getCommonCodeSignersForJar(Unknown Source)
	at com.sun.javaws.security.SigningInfo.check(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResourcesHelper(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:744)

**Comment by evsinev** [comment]
Thank you. I've added assemble.sh to the server dir.

Could you please attach jarsigner output:
```
jarsigner -verify -verbose mpos.jar
```

**Comment by DwarfNumber2** [comment]
The problem was solved by adding certificate to console, my fault.


Another problem now:

java.lang.NoSuchMethodError: gnu.io.CommPortIdentifier.addPortName(Ljava/lang/String;ILgnu/io/spi/CommDriver;)V
	at gnu.io.DriverContext.registerPort(DriverContext.java:149)
	at gnu.io.impl.serial.RXTXCommDriver.registerValidPorts(RXTXCommDriver.java:236)
	at gnu.io.impl.serial.RXTXCommDriver.registerScannedPorts(RXTXCommDriver.java:709)
	at gnu.io.impl.serial.RXTXCommDriver.initialize(RXTXCommDriver.java:254)
	at gnu.io.DriverManager.loadDrivers(DriverManager.java:130)
	at com.payneteasy.android.sdk.reader.miurarxtx.MiuraRxTxReader.findPortIdentifier(MiuraRxTxReader.java:76)
	at com.payneteasy.android.sdk.reader.miurarxtx.MiuraRxTxReader.start(MiuraRxTxReader.java:52)
	at com.payneteasy.webstart.client.Main.startPayment(Main.java:104)
	at com.payneteasy.webstart.client.Main.main(Main.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.sun.javaws.Launcher.executeApplication(Unknown Source)
	at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:744)

**Comment by DwarfNumber2** [comment]
But without Miura connection to my laptop jnlp runs corretcly and shows "There no open COM ports" message.

dwarf_2@dwarf-2:~$ dmesg
[42833.920022] usb 2-1: USB disconnect, device number 9
[42834.294108] usb 2-1: new high-speed USB device number 10 using xhci_hcd
[42834.316610] usb 2-1: New USB device found, idVendor=0525, idProduct=a4a7
[42834.316620] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[42834.316625] usb 2-1: Product: Gadget Serial v2.4
[42834.316630] usb 2-1: Manufacturer: Linux 2.6.31-506-g30df573M000-OS-V7-5 with fsl-us
[42834.321037] cdc_acm 2-1:2.0: This device cannot do calls on its own. It is not a modem.
[42834.321150] cdc_acm 2-1:2.0: ttyACM0: USB ACM device

**Comment by evsinev** [comment]
There are several ways to fix it:

1. Set System.setProperty("os.name", "Linux-all-ports") before calling rxtx library.
So RXTXCommDriver can inspect /dev/ directory for serial devices.

2. Link /dev/ttyACM0 to /dev/USBS0 
Because  RXTXCommDriver can handle a few ports:
```
if (osName.equals("Linux")) {
                String[] temp = {
                    "ttyS", // linux Serial Ports
                    "ttySA", // for the IPAQs
                    "ttyUSB", // for USB frobs
                    "rfcomm", // bluetooth serial device
                    "ttyircomm", // linux IrCommdevices (IrDA serial emu)
                };
```

And don't forget to set permissions for your user to read and write to serial device.

**Comment by DwarfNumber2** [comment]
The following rules doesn't help:
KERNEL=="ttyACM[0-9]*", SYMLINK+="ttyUSB9"

**Comment by evsinev** [comment]
As I understand you have /dev/ttyUSB9 symlink when connecting a Miura device.

You can add "/dev/ttyACM0" to https://github.com/payneteasy/reader-example/blob/master/app-3-webstart/client/src/main/java/com/payneteasy/webstart/client/Main.java
to help rxtx find the port.
```
CardReaderInfo readerInfo = new CardReaderInfo("Miura", CardReaderType.MIURA, "/dev/ttyACM0");
```

**Comment by evsinev** [comment]
Also you can run client without java WebStart to speed up debugging, just run class
com.payneteasy.webstart.client.Main 
with parameters 
-amount 1.0 -currency RUB -description=descr -invoice=123-1234

**Comment by DwarfNumber2** [comment]
dwarf_2@dwarf-2:~/libs/reader-example-master/app-3-webstart$ java -cp server/src/main/resources/web/mpos.jar com.payneteasy.webstart.client.Main -amount 1.0 -currency RUB -description=descr -invoice=123-1234
Version 4
2015.09.23 20:06:04.072 [main] DEBUG com.payneteasy.webstart.client.Main - Starting reader manager ...
2015.09.23 20:06:04.090 [main] DEBUG c.p.a.s.r.miurarxtx.MiuraRxTxReader - Setting system property gnu.io.SerialPorts to /dev/ttyACM0 ...
сен 23, 2015 8:06:04 PM gnu.io.LibraryLoader load FINEST: try to load hinted lib from resource
сен 23, 2015 8:06:04 PM gnu.io.LibraryLoader load FINE: Loaded JNI lib /tmp/librxtxSerial-linux-x86_64-4634029434981089113.so (extracted from resource)
Exception in thread "main" java.lang.NoSuchMethodError: gnu.io.CommPortIdentifier.addPortName(Ljava/lang/String;ILgnu/io/spi/CommDriver;)V
	at gnu.io.DriverContext.registerPort(DriverContext.java:149)
	at gnu.io.impl.serial.RXTXCommDriver.addSpecifiedPorts(RXTXCommDriver.java:268)
	at gnu.io.impl.serial.RXTXCommDriver.registerSpecifiedPorts(RXTXCommDriver.java:299)
	at gnu.io.impl.serial.RXTXCommDriver.initialize(RXTXCommDriver.java:252)
	at gnu.io.DriverManager.loadDrivers(DriverManager.java:130)
	at com.payneteasy.android.sdk.reader.miurarxtx.MiuraRxTxReader.findPortIdentifier(MiuraRxTxReader.java:76)
	at com.payneteasy.android.sdk.reader.miurarxtx.MiuraRxTxReader.start(MiuraRxTxReader.java:52)
	at com.payneteasy.webstart.client.Main.startPayment(Main.java:104)
	at com.payneteasy.webstart.client.Main.main(Main.java:52)


With System variable and port finding help in reader info initialization.

**Comment by evsinev** [comment]
I think some rxtx classes has been included from the old rxtx-library version.

Could you please check the CommPortIdentifier.addPortName(...) and DriverContext.registerPort(...)
methods in the classes (.class) and source files (.java).

**Comment by DwarfNumber2** [comment]
Seems, that System property in not actua;;y correct

Exception in thread "main" java.lang.AssertionError: Platform not recognized
	at sun.nio.fs.DefaultFileSystemProvider.create(DefaultFileSystemProvider.java:66)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:108)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.access$000(FileSystems.java:89)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:98)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:96)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:96)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:90)
	at java.nio.file.FileSystems.getDefault(FileSystems.java:176)
	at java.io.File.toPath(File.java:2234)
	at sun.font.FcFontConfiguration.writeFcInfo(FcFontConfiguration.java:391)
	at sun.font.FcFontConfiguration.init(FcFontConfiguration.java:100)
	at sun.font.FcFontConfiguration.<init>(FcFontConfiguration.java:75)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:747)
	at sun.font.SunFontManager$2.run(SunFontManager.java:430)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:375)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:32)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:433)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at sun.font.SunFontManager.getInstance(SunFontManager.java:249)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1039)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1623)
	at javax.swing.text.PlainView.calculateLongestLine(PlainView.java:639)
	at javax.swing.text.PlainView.updateMetrics(PlainView.java:209)
	at javax.swing.text.PlainView.updateDamage(PlainView.java:527)
	at javax.swing.text.PlainView.insertUpdate(PlainView.java:451)
	at javax.swing.plaf.basic.BasicTextUI$RootView.insertUpdate(BasicTextUI.java:1610)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.insertUpdate(BasicTextUI.java:1869)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1712)
	at javax.swing.JTextArea.<init>(JTextArea.java:212)
	at javax.swing.JTextArea.<init>(JTextArea.java:150)
	at com.payneteasy.webstart.client.MainPanel.<init>(MainPanel.java:25)
	at com.payneteasy.webstart.client.Main.main(Main.java:50)

**Comment by DwarfNumber2** [comment]
In case of commenting system porperty - error is still the same:
Exception in thread "main" java.lang.NoSuchMethodError: gnu.io.CommPortIdentifier.addPortName(Ljava/lang/String;ILgnu/io/spi/CommDriver;)V
	at gnu.io.DriverContext.registerPort(DriverContext.java:149)

Classes are new in target folder.

**Comment by evsinev** [comment]
Could you please share your mpos.jar file.

**Comment by DwarfNumber2** [comment]
Was trying several variants: it can't "talk" with ACM port.
Are there any variants to trun CDC ACM mode on Miura device?

**Comment by evsinev** [comment]
The problem was solved.
There is an old rxtx jar in the system java library.
